
modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.18.2-1.0.4"
displayName="Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, Grimmauld, CDAGaming, TelepathicGrunt, ConductiveFoam, simibubi, Jozufozu, bagel, Silk, SkySom, Eutro and many others!"
authors="vectorwing"
description="A lightweight farming and cooking expansion for Minecraft!"
itemIcon="farmersdelight:stove"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
