
modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.16.3-0.2.4"
displayName="Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, simibubi, Silk, SkySom and many other wonderful people!"
authors="vectorwing, Grimmauld"
description="A lightweight farming expansion for Minecraft. Harvest, cook and explore!"

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
